name: Newt
version: 1.0.0
slug: newt
description: Tunneling client to connect Home Assistant to Pangolin.
url: https://github.com/homeassistant-apps/app-newt
startup: services
init: false
arch:
- aarch64
- amd64
schema:
  pangolin_endpoint: str
  newt_id: str
  newt_secret: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
image: ghcr.io/homeassistant-apps/newt/{arch}
